import { createVariantUiColor, opacity, type UiColor } from 'vscode-typed-theme-generator';
import { colors, Var, variant } from './color';

const uiColor: UiColor = {
  // base
  focusBorder: Var.deepPurpleA700,
  foreground: Var.blueGrey100,
  'widget.border': Var.deepPurpleA200,
  errorForeground: Var.pink700,
  'icon.foreground': Var.deepPurpleA200,
  // text
  'textLink.activeForeground': Var.orange500,
  'textLink.foreground': Var.blue500,
  // button
  'button.background': Var.deepPurpleA700,
  'button.secondaryBackground': Var.deepOrangeA700,
  'checkbox.background': Var.input,
  // dropdown
  'dropdown.background': Var.input,
  'dropdown.listBackground': Var.input,
  // input
  'input.background': Var.input,
  'inputOption.activeBackground': Var.deepPurpleA700,
  'inputValidation.errorBackground': Var.pink900,
  'inputValidation.errorBorder': Var.pink900,
  'inputValidation.infoBackground': Var.lightBlue900,
  'inputValidation.infoBorder': Var.lightBlue900,
  'inputValidation.warningBackground': Var.orange900,
  'inputValidation.warningBorder': Var.orange900,
  // badge
  'badge.background': Var.deepPurpleA700,
  // progress
  'progressBar.background': Var.deepPurpleA700,
  // listTree
  'list.dropBackground': Var.bgSm,
  'list.activeSelectionBackground': Var.purple900,
  'list.hoverBackground': Var.bgLg,
  'list.inactiveSelectionBackground': Var.bgLg,
  'list.errorForeground': Var.pink500,
  'list.warningForeground': Var.orange500,
  // activityBar
  'activityBar.background': Var.bgBs,
  'activityBar.inactiveForeground': opacity(Var.deepPurple50, 0.4),
  'activityBar.foreground': Var.deepPurpleA400,
  'activityBar.activeBorder': Var.deepPurpleA400,
  'activityBarBadge.background': Var.deepPurpleA700,
  // sideBar
  'sideBar.background': Var.bgXxs,
  // Minimap
  'minimapSlider.background': opacity(Var.grey50, 0.2),
  'minimapSlider.hoverBackground': opacity(Var.grey50, 0.3),
  'minimapSlider.activeBackground': opacity(Var.grey50, 0.3),
  // editorGroupTabs
  'editorGroupHeader.tabsBackground': Var.bgBs,
  'tab.inactiveBackground': Var.bgBs,
  'tab.activeBackground': Var.bgXs,
  'tab.activeBorder': Var.deepPurpleA400,
  'tab.activeForeground': Var.grey50,
  'tab.inactiveForeground': Var.grey500,
  'tab.activeModifiedBorder': Var.amber500,
  // editor
  'editor.foreground': Var.blueGrey100,
  'editor.background': Var.bgBs,
  'editorLineNumber.foreground': Var.blueGrey700,
  'editorLineNumber.activeForeground': Var.purpleA400,
  'editor.selectionBackground': opacity(Var.lightBlue500, 0.3),
  'editor.inactiveSelectionBackground': opacity(Var.lightBlue500, 0.2),
  'editor.selectionHighlightBackground': opacity(Var.lightBlue700, 0.3),
  'editor.selectionHighlightBorder': colors.transparency,
  'editor.wordHighlightBackground': opacity(Var.blue700, 0.5),
  'editor.wordHighlightBorder': colors.transparency,
  'editor.wordHighlightStrongBackground': opacity(Var.pink700, 0.5),
  'editor.wordHighlightStrongBorder': colors.transparency,
  'editor.findMatchBackground': opacity(Var.amber900, 0.25),
  'editor.findMatchHighlightBackground': opacity(Var.amber900, 0.2),
  'editor.findRangeHighlightBackground': opacity(Var.amber900, 0.1),
  'editor.findMatchBorder': colors.transparency,
  'editor.findMatchHighlightBorder': colors.transparency,
  'editor.findRangeHighlightBorder': colors.transparency,
  'editor.lineHighlightBackground': opacity(Var.blueGrey700, 0.3),
  'editor.lineHighlightBorder': colors.transparency,
  'editorUnicodeHighlight.background': opacity(Var.yellow700, 0.1),
  'editorUnicodeHighlight.border': opacity(Var.yellow700, 0.4),
  'editorIndentGuide.background': Var.blueGrey800,
  'editorIndentGuide.activeBackground': Var.blueGrey400,
  'editorRuler.foreground': opacity(Var.blueGrey700, 0.25),
  'editorLightBulb.foreground': Var.yellow500,
  'editorLightBulbAutoFix.foreground': Var.blue500,
  'editorBracketMatch.background': opacity(Var.blueGrey300, 0.2),
  'editorBracketMatch.border': opacity(Var.blueGrey300, 0.7),
  'editorBracketHighlight.foreground1': Var.cyan300,
  'editorBracketHighlight.foreground2': Var.deepOrange300,
  'editorBracketHighlight.foreground3': Var.purple300,
  'editorBracketHighlight.foreground4': Var.lime300,
  'editorBracketHighlight.foreground5': Var.blue300,
  'editorBracketHighlight.foreground6': Var.amber300,
  'editorBracketHighlight.unexpectedBracket.foreground': Var.pink300,
  'editorBracketPairGuide.activeBackground1': Var.cyan300,
  'editorBracketPairGuide.activeBackground2': Var.deepOrange300,
  'editorBracketPairGuide.activeBackground3': Var.purple300,
  'editorBracketPairGuide.activeBackground4': Var.lime300,
  'editorBracketPairGuide.activeBackground5': Var.blue300,
  'editorBracketPairGuide.activeBackground6': Var.amber300,
  'editorBracketPairGuide.background1': opacity(Var.cyan300, 0.6),
  'editorBracketPairGuide.background2': opacity(Var.deepOrange300, 0.6),
  'editorBracketPairGuide.background3': opacity(Var.purple300, 0.6),
  'editorBracketPairGuide.background4': opacity(Var.lime300, 0.6),
  'editorBracketPairGuide.background5': opacity(Var.blue300, 0.6),
  'editorBracketPairGuide.background6': opacity(Var.amber300, 0.6),
  'editor.foldBackground': opacity(Var.indigo700, 0.3),
  'editorOverviewRuler.modifiedForeground': Var.blue700,
  'editorOverviewRuler.addedForeground': Var.green700,
  'editorOverviewRuler.deletedForeground': Var.red700,
  'editorOverviewRuler.errorForeground': Var.pink700,
  'editorOverviewRuler.warningForeground': Var.orange700,
  'editorOverviewRuler.infoForeground': Var.lightBlue700,
  'editorError.foreground': Var.pink700,
  'editorWarning.foreground': Var.orange700,
  'editorInfo.foreground': Var.lightBlue700,
  'editorHint.foreground': Var.yellow700,
  'problemsErrorIcon.foreground': Var.pink700,
  'problemsWarningIcon.foreground': Var.orange700,
  'problemsInfoIcon.foreground': Var.lightBlue700,
  'editorGutter.modifiedBackground': Var.blue700,
  'editorGutter.addedBackground': Var.green700,
  'editorGutter.deletedBackground': Var.red700,
  // diffEditor
  'diffEditor.insertedTextBackground': opacity(Var.green700, 0.4),
  'diffEditor.insertedLineBackground': opacity(Var.green700, 0.2),
  'diffEditor.removedTextBackground': opacity(Var.red700, 0.4),
  'diffEditor.removedLineBackground': opacity(Var.red700, 0.2),
  'diffEditorGutter.insertedLineBackground': opacity(Var.green700, 0.1),
  'diffEditorGutter.removedLineBackground': opacity(Var.red700, 0.1),
  'diffEditor.diagonalFill': opacity(Var.blueGrey700, 0.5),
  // editorWidget
  'editorWidget.background': Var.bgBs,
  'editorWidget.border': Var.deepPurpleA700,
  'editorMarkerNavigationError.background': Var.pink700,
  'editorMarkerNavigationWarning.background': Var.orange700,
  'editorMarkerNavigationInfo.background': Var.lightBlue700,
  // peekView
  'peekView.border': Var.deepPurpleA700,
  'peekViewEditor.background': opacity(Var.deepPurpleA700, 0.05),
  'peekViewResult.background': opacity(Var.deepPurpleA700, 0.05),
  'peekViewEditor.matchHighlightBackground': opacity(Var.orange500, 0.2),
  'peekViewTitle.background': Var.bgBs,
  // mergeConflict
  'merge.currentHeaderBackground': opacity(Var.green700, 0.4),
  'merge.currentContentBackground': opacity(Var.green700, 0.2),
  'merge.incomingHeaderBackground': opacity(Var.blue700, 0.4),
  'merge.incomingContentBackground': opacity(Var.blue700, 0.2),
  'editorOverviewRuler.currentContentForeground': Var.green500,
  'editorOverviewRuler.incomingContentForeground': Var.blue500,
  'mergeEditor.change.background': opacity(Var.lime700, 0.1),
  'mergeEditor.change.word.background': opacity(Var.lime700, 0.3),
  'mergeEditor.conflict.unhandledUnfocused.border': Var.orange700,
  'mergeEditor.conflict.unhandledFocused.border': Var.orange500,
  'mergeEditor.conflict.handledUnfocused.border': Var.blue700,
  'mergeEditor.conflict.handledFocused.border': Var.blue500,
  'mergeEditor.conflict.handled.minimapOverViewRuler': Var.blue500,
  'mergeEditor.conflict.unhandled.minimapOverViewRuler': Var.orange500,
  // panel
  'panelTitle.activeBorder': Var.deepPurpleA700,
  'panelInput.border': Var.deepPurpleA700,
  'panelSection.border': Var.deepPurpleA700,
  'panelSectionHeader.border': Var.deepPurpleA700,
  // statusBar
  'statusBar.background': Var.bgBs,
  'statusBar.debuggingBackground': Var.deepOrange900,
  'statusBar.noFolderBackground': Var.bgBs,
  'statusBarItem.prominentBackground': Var.deepPurpleA700,
  'statusBarItem.remoteBackground': Var.deepPurpleA700,
  'statusBarItem.errorBackground': Var.pink700,
  'statusBarItem.warningBackground': Var.orange700,
  // titleBar
  'titleBar.activeBackground': Var.bgBs,
  'titleBar.inactiveBackground': Var.bgXs,
  // menuBar
  'menu.background': Var.bgSm,
  // Command Center colors
  'commandCenter.border': Var.deepPurpleA700,
  // notification
  'notificationCenterHeader.background': Var.bgSm,
  'notifications.background': Var.bgSm,
  'notifications.border': Var.deepPurpleA700,
  // extension
  'extensionButton.separator': Var.deepPurpleA700,
  'extensionBadge.remoteBackground': Var.deepPurpleA200,
  'extensionIcon.starForeground': Var.amber500,
  'extensionIcon.verifiedForeground': Var.blue500,
  'extensionIcon.preReleaseForeground': Var.orange500,
  'extensionIcon.sponsorForeground': Var.yellow500,
  // Keybinding label colors
  'keybindingLabel.background': Var.deepPurpleA700,
  // integratedTerminal
  'terminal.ansiBlack': Var.blueGrey900,
  'terminal.ansiBlue': Var.blue900,
  'terminal.ansiBrightBlack': Var.blueGrey700,
  'terminal.ansiBrightBlue': Var.blue500,
  'terminal.ansiBrightCyan': Var.cyan500,
  'terminal.ansiBrightGreen': Var.green500,
  'terminal.ansiBrightMagenta': Var.pink500,
  'terminal.ansiBrightRed': Var.red500,
  'terminal.ansiBrightWhite': Var.blueGrey300,
  'terminal.ansiBrightYellow': Var.yellow500,
  'terminal.ansiCyan': Var.cyan700,
  'terminal.ansiGreen': Var.green700,
  'terminal.ansiMagenta': Var.pink700,
  'terminal.ansiRed': Var.red700,
  'terminal.ansiWhite': Var.blueGrey500,
  'terminal.ansiYellow': Var.yellow700,
  // git
  'gitDecoration.addedResourceForeground': opacity(Var.green500, 0.8),
  'gitDecoration.modifiedResourceForeground': opacity(Var.blue500, 0.8),
  'gitDecoration.deletedResourceForeground': opacity(Var.red500, 0.8),
  'gitDecoration.renamedResourceForeground': opacity(Var.indigo500, 0.8),
  'gitDecoration.stageModifiedResourceForeground': Var.blue300,
  'gitDecoration.stageDeletedResourceForeground': Var.red300,
  'gitDecoration.untrackedResourceForeground': opacity(Var.green500, 0.8),
  'gitDecoration.conflictingResourceForeground': Var.orange300,
  'gitDecoration.submoduleResourceForeground': Var.cyan300,
  // settingsEditor
  'settings.modifiedItemIndicator': Var.amber700,
  'settings.focusedRowBorder': Var.deepPurpleA700,
  // Snippets colors
  'editor.snippetTabstopHighlightBackground': opacity(Var.deepPurpleA400, 0.5),
  'editor.snippetFinalTabstopHighlightBorder': Var.deepOrangeA400,
  // Breadcrumbs colors
  'breadcrumbPicker.background': Var.bgSm,
  // Symbol Icons colors
  'symbolIcon.arrayForeground': Var.orangeA200,
  'symbolIcon.booleanForeground': Var.redA200,
  'symbolIcon.classForeground': Var.yellowA200,
  'symbolIcon.colorForeground': Var.lightGreenA400,
  'symbolIcon.constantForeground': Var.redA200,
  'symbolIcon.constructorForeground': Var.tealA200,
  'symbolIcon.enumeratorForeground': Var.yellowA200,
  'symbolIcon.enumeratorMemberForeground': Var.lightBlueA200,
  // 'symbolIcon.eventForeground': '',
  'symbolIcon.fieldForeground': Var.lightBlueA200,
  // 'symbolIcon.fileForeground': '',
  // 'symbolIcon.folderForeground': '',
  'symbolIcon.functionForeground': Var.tealA200,
  'symbolIcon.interfaceForeground': Var.yellowA200,
  'symbolIcon.keyForeground': Var.lightGreenA400,
  'symbolIcon.keywordForeground': Var.deepPurpleA200,
  'symbolIcon.methodForeground': Var.tealA200,
  'symbolIcon.moduleForeground': Var.orangeA200,
  'symbolIcon.namespaceForeground': Var.orangeA200,
  'symbolIcon.nullForeground': Var.redA200,
  'symbolIcon.numberForeground': Var.pink200,
  'symbolIcon.objectForeground': Var.orangeA200,
  'symbolIcon.operatorForeground': Var.lightGreenA400,
  'symbolIcon.packageForeground': Var.orangeA200,
  'symbolIcon.propertyForeground': Var.lightBlueA200,
  // 'symbolIcon.referenceForeground': '',
  // 'symbolIcon.snippetForeground': '',
  'symbolIcon.stringForeground': Var.green200,
  'symbolIcon.structForeground': Var.yellowA200,
  'symbolIcon.textForeground': Var.blueGrey100,
  'symbolIcon.typeParameterForeground': Var.deepOrangeA200,
  'symbolIcon.unitForeground': Var.lightGreenA400,
  'symbolIcon.variableForeground': Var.orangeA200,
};

export const variantUiColor = createVariantUiColor(uiColor, variant);
